language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_b63156592b1a_key -iv $encrypted_b63156592b1a_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
